import 'package:go_router/go_router.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../features/auth/presentation/providers/auth_provider.dart';
import '../../features/auth/presentation/screens/splash_screen.dart';
import '../../features/auth/presentation/screens/login_screen.dart';
import '../../features/auth/presentation/screens/register_screen.dart';
import '../../features/home/presentation/screens/home_screen.dart';
import '../../features/map/presentation/screens/map_screen.dart';
import '../../features/trip/presentation/screens/trip_live_screen.dart';
import '../../features/trip/presentation/screens/trip_summary_screen.dart';
import '../../features/trip/presentation/screens/trip_detail_screen.dart';
import '../../features/trip/presentation/providers/trip_live_provider.dart';
import '../../features/leaderboard/presentation/screens/leaderboard_screen.dart';
import '../../features/crew/presentation/screens/crew_screen.dart';
import '../../features/chat/presentation/screens/crew_chat_screen.dart';
import '../../features/car_spotting/presentation/screens/car_spotting_feed_screen.dart';
import '../../features/profile/presentation/screens/profile_screen.dart';
import '../../features/missions/presentation/screens/missions_screen.dart';
import '../../features/achievements/presentation/screens/achievements_screen.dart';
import '../../features/events/presentation/screens/events_screen.dart';
import '../../features/settings/presentation/screens/settings_screen.dart';
import '../../features/notifications/presentation/screens/notifications_screen.dart';
import '../widgets/main_shell.dart';

part 'app_router.g.dart'; // generated by riverpod_generator (riverpod build_runner)

/// Route path constants — single source of truth, avoid magic strings.
class AppRoutes {
  AppRoutes._();
  static const splash = '/';
  static const login = '/login';
  static const register = '/register';

  static const home = '/home';
  static const map = '/map';
  static const tripLive = '/trip/live';
  static const tripSummary = '/trip/summary';
  static const tripDetail = '/trip/:tripId';
  static const leaderboard = '/leaderboard';
  static const crew = '/crew';
  static const crewChat = '/crew/chat';
  static const carSpotting = '/car-spotting';
  static const profile = '/profile';
  static const missions = '/missions';
  static const achievements = '/achievements';
  static const events = '/events';
  static const settings = '/settings';
  static const notifications = '/notifications';
}

@riverpod
GoRouter appRouter(AppRouterRef ref) {
  final authState = ref.watch(authStateProvider);

  return GoRouter(
    initialLocation: AppRoutes.splash,
    debugLogDiagnostics: false,
    redirect: (context, state) {
      final isLoggedIn = authState.valueOrNull != null;
      final isAuthRoute = state.matchedLocation == AppRoutes.login ||
          state.matchedLocation == AppRoutes.register;
      final isSplash = state.matchedLocation == AppRoutes.splash;

      if (isSplash) return null; // splash handles its own timed redirect
      if (!isLoggedIn && !isAuthRoute) return AppRoutes.login;
      if (isLoggedIn && isAuthRoute) return AppRoutes.home;
      return null;
    },
    routes: [
      GoRoute(path: AppRoutes.splash, builder: (c, s) => const SplashScreen()),
      GoRoute(path: AppRoutes.login, builder: (c, s) => const LoginScreen()),
      GoRoute(
          path: AppRoutes.register, builder: (c, s) => const RegisterScreen()),

      // Full-screen routes (outside bottom-nav shell)
      GoRoute(
          path: AppRoutes.tripLive, builder: (c, s) => const TripLiveScreen()),
      GoRoute(
        path: AppRoutes.tripSummary,
        builder: (c, s) => TripSummaryScreen(summary: s.extra as TripSummary),
      ),
      GoRoute(
        path: AppRoutes.tripDetail,
        builder: (c, s) =>
            TripDetailScreen(tripId: s.pathParameters['tripId']!),
      ),
      GoRoute(
          path: AppRoutes.crewChat, builder: (c, s) => const CrewChatScreen()),
      GoRoute(
          path: AppRoutes.achievements,
          builder: (c, s) => const AchievementsScreen()),
      GoRoute(path: AppRoutes.events, builder: (c, s) => const EventsScreen()),
      GoRoute(
          path: AppRoutes.settings, builder: (c, s) => const SettingsScreen()),
      GoRoute(
          path: AppRoutes.notifications,
          builder: (c, s) => const NotificationsScreen()),

      // Bottom-nav shell (7 primary tabs)
      ShellRoute(
        builder: (context, state, child) => MainShell(child: child),
        routes: [
          GoRoute(path: AppRoutes.home, builder: (c, s) => const HomeScreen()),
          GoRoute(
              path: AppRoutes.missions,
              builder: (c, s) => const MissionsScreen()),
          GoRoute(path: AppRoutes.map, builder: (c, s) => const MapScreen()),
          GoRoute(
              path: AppRoutes.carSpotting,
              builder: (c, s) => const CarSpottingFeedScreen()),
          GoRoute(
              path: AppRoutes.profile,
              builder: (c, s) => const ProfileScreen()),
          GoRoute(
              path: AppRoutes.leaderboard,
              builder: (c, s) => const LeaderboardScreen()),
          GoRoute(path: AppRoutes.crew, builder: (c, s) => const CrewScreen()),
        ],
      ),
    ],
  );
}
